# DataCamp Data Engineer Associate Certificate Prep
- https://app.datacamp.com/learn/fast-tracks/data-engineer-associate/plan
- Focus on Competency 2, 3, and 5 (Python programming)

## Competency 2: Data Management in Python

### 1. Logic, Control Flow and Filtering
- Comparison Operators
- Boolean Operators

In [2]:
import numpy as np

# array(), a function part of the Numpy Library
# (): function call. []: a Python list. The function call array() convert the Pytyon list into a Numpy array.

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight/np_height**2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [29]:
# apply a Boolean indexing or boolean masking to the `bmi` array.

print(bmi[bmi>23])


# concise and comonly accepted
# `&` is a bitwise operator used for element-wise logical AND operations on arrays. 

print(bmi[(bmi > 21) & (bmi < 24)])

# for explicitness or complex conditions. Masked array:
print(bmi[np.logical_and(bmi > 21, bmi < 24)])
print(bmi[np.logical_not(bmi <= 21, bmi >= 24)])

# boolean array
print(np.logical_and(bmi > 21, bmi < 24))
print(np.logical_not(bmi <= 21, bmi >= 24))

[24.7473475]
[21.85171573 21.75028214 21.44127836]
[21.85171573 21.75028214 21.44127836]
[21.85171573 21.75028214 24.7473475  21.44127836]
[ True False  True False  True]
[ True False  True  True  True]


In [5]:
bmi>23

array([False, False, False,  True, False])

In [14]:
print(True == 1)
print(True > False)

True
True


In [27]:
my_kitchen = 18.0
your_kitchen = 14.0

print(my_kitchen > 10 and my_kitchen < 18)
print(my_kitchen < 14 and my_kitchen > 17)
print(my_kitchen*2 < your_kitchen*3)

False
False
True


### 2. Transforming DataFrames
- Sorting and subsetting
- Introducing DataFrames

In [18]:
# Create a list of dictionaries for the dogs' data
import pandas as pd

dogs = pd.DataFrame([
    {
        "name": "Bella",
        "breed": "Labrador",
        "color": "Brown",
        "height_cm": 56,
        "weight_kg": 22,
        "date_of_birth": "2013-07-01"
    },
    {
        "name": "Charlie",
        "breed": "Poodle",
        "color": "Black",
        "height_cm": 43,
        "weight_kg": 22,
        "date_of_birth": "2016-09-16"
    },
    {
        "name": "Lucy",
        "breed": "Chow Chow",
        "color": "Brown",
        "height_cm": 46,
        "weight_kg": 22,
        "date_of_birth": "2014-08-25"
    },
    {
        "name": "Cooper",
        "breed": "Schnauzer",
        "color": "Gray",
        "height_cm": 49,
        "weight_kg": 17,
        "date_of_birth": "2011-12-11"
    },
    {
        "name": "Max",
        "breed": "Labrador",
        "color": "Black",
        "height_cm": 59,
        "weight_kg": 29,
        "date_of_birth": "2017-01-20"
    },
    {
        "name": "Stella",
        "breed": "Chihuahua",
        "color": "Tan",
        "height_cm": 18,
        "weight_kg": 2.2,
        "date_of_birth": "2015-04-20"
    },
    {
        "name": "Bernie",
        "breed": "St. Bernard",
        "color": "White",
        "height_cm": 77,
        "weight_kg": 74,
        "date_of_birth": "2018-02-27"
    }
])

In [47]:
# various sorting queries

queries = [
    dogs.sort_values("weight_kg"), # sort by a col, ascending
    dogs.sort_values("weight_kg", ascending = False), # sort by a col, descending
    dogs.sort_values(["weight_kg", "height_cm"], ascending = [True, False]) # sort by multi-orders
]

for result in queries:
    print(result)
    print("\n")

      name        breed  color  height_cm  weight_kg date_of_birth
5   Stella    Chihuahua    Tan         18        2.2    2015-04-20
3   Cooper    Schnauzer   Gray         49       17.0    2011-12-11
0    Bella     Labrador  Brown         56       22.0    2013-07-01
1  Charlie       Poodle  Black         43       22.0    2016-09-16
2     Lucy    Chow Chow  Brown         46       22.0    2014-08-25
4      Max     Labrador  Black         59       29.0    2017-01-20
6   Bernie  St. Bernard  White         77       74.0    2018-02-27


      name        breed  color  height_cm  weight_kg date_of_birth
6   Bernie  St. Bernard  White         77       74.0    2018-02-27
4      Max     Labrador  Black         59       29.0    2017-01-20
0    Bella     Labrador  Brown         56       22.0    2013-07-01
1  Charlie       Poodle  Black         43       22.0    2016-09-16
2     Lucy    Chow Chow  Brown         46       22.0    2014-08-25
3   Cooper    Schnauzer   Gray         49       17.0    2011

In [53]:
# various subsetting queries

queries = [
    # subset columns
    dogs["height_cm"], # subset a single col
    dogs[["breed", "height_cm"]], # inner brackets: pass a list. outer brackets: subset multiple cols
    
    # subset rows
    dogs[dogs["height_cm"] > 50], # subset rows. inner bracket: boolean mask
    dogs[dogs["breed"] == "Labrador"],
    dogs[dogs["date_of_birth"] < "2015-01-01"],

    dogs[(dogs["breed"] == "Labrador") & (dogs["color"] == "Brown")], # subset rows based on single value. & and round brackets are required
    dogs[dogs["color"].isin(["Black", "Brown"])] #isin is a method. subset multi-rows
    
]

for result in queries:
    print(result)
    print("\n")

0    56
1    43
2    46
3    49
4    59
5    18
6    77
Name: height_cm, dtype: int64


         breed  height_cm
0     Labrador         56
1       Poodle         43
2    Chow Chow         46
3    Schnauzer         49
4     Labrador         59
5    Chihuahua         18
6  St. Bernard         77


     name        breed  color  height_cm  weight_kg date_of_birth
0   Bella     Labrador  Brown         56       22.0    2013-07-01
4     Max     Labrador  Black         59       29.0    2017-01-20
6  Bernie  St. Bernard  White         77       74.0    2018-02-27


    name     breed  color  height_cm  weight_kg date_of_birth
0  Bella  Labrador  Brown         56       22.0    2013-07-01
4    Max  Labrador  Black         59       29.0    2017-01-20


     name      breed  color  height_cm  weight_kg date_of_birth
0   Bella   Labrador  Brown         56       22.0    2013-07-01
2    Lucy  Chow Chow  Brown         46       22.0    2014-08-25
3  Cooper  Schnauzer   Gray         49       17.0    201

In [69]:
# various DataFrame exploration functions

queries = [
    # methods
    dogs.head(3),
    dogs.info(),
    dogs.describe(),

    # attributes
    # this is an attribute returning a tuple, not method. It doesn't have parentheses. 
    dogs.shape,
    dogs.columns,
    dogs.index, # row labels are stored in dot-index
    dogs.dtypes
]

for result in queries:
    print(result)
    print("\n")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           7 non-null      object 
 1   breed          7 non-null      object 
 2   color          7 non-null      object 
 3   height_cm      7 non-null      int64  
 4   weight_kg      7 non-null      float64
 5   date_of_birth  7 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 464.0+ bytes
      name      breed  color  height_cm  weight_kg date_of_birth
0    Bella   Labrador  Brown         56       22.0    2013-07-01
1  Charlie     Poodle  Black         43       22.0    2016-09-16
2     Lucy  Chow Chow  Brown         46       22.0    2014-08-25


None


       height_cm  weight_kg
count   7.000000   7.000000
mean   49.714286  26.885714
std    17.960274  22.371666
min    18.000000   2.200000
25%    44.500000  19.500000
50%    49.000000  22.000000
75%    57.500000

### 4. Regular Expressions for Pattern Matching

In [104]:
# r'st\d\s\w{3,10}'
# r: raw string
# st: normal characterse match themselves - s followed by a t
# metacharacters: 
# \d (a digit, number) 
# \D (a non-digit, non-number) 
# \s (a white space)
# \S (a non-white space)
# \w (a word character, or represent ideas)
# \W (a non-word, e.g., dollar sign)
# {3, 10} (the character immediately to the left, \w, should appear between 3 and 10 times)

In [2]:
import re

string1 = '''These XP are awarded based on the completion of lessons,
    exercises within a course, or other learning activities. 
    As users progress through courses and successfully complete exercises, they accumulate XP.

    The XP system is designed to motivate learners, encourage consistent learning behavior, 
    and provide a sense of accomplishment as users advance through the courses and exercises on the platform. 
    '''


In [94]:
# Find how many sub-strings match
print(re.findall(r"XP", string1))

# Split the long sentence by period mark
print(re.split(r'\.', string1))

# Replace word
re.sub(r"XP", "Exp Points", string1)


['XP', 'XP', 'XP']
['These XP are awarded based on the completion of lessons,\n    exercises within a course, or other learning activities', ' \n    As users progress through courses and successfully complete exercises, they accumulate XP', '\n\n    The XP system is designed to motivate learners, encourage consistent learning behavior, \n    and provide a sense of accomplishment as users advance through the courses and exercises on the platform', ' \n    ']


'These Exp Points are awarded based on the completion of lessons,\n    exercises within a course, or other learning activities. \n    As users progress through courses and successfully complete exercises, they accumulate Exp Points.\n\n    The Exp Points system is designed to motivate learners, encourage consistent learning behavior, \n    and provide a sense of accomplishment as users advance through the courses and exercises on the platform. \n    '

In [97]:
# Find digit, non-digit
string2 = "The winners are: User9, UserN, User8"
print(re.findall(r"User\d", string2))
print(re.findall(r"User\D", string2))
print(re.findall(r"User\w", string2))

['User9', 'User8']
['UserN']
['User9', 'UserN', 'User8']


In [103]:
# Find dollar sign + number
string3 = "This skirt is on sale, only $5 today! We also have robot-constumes on sale."
print(re.findall(r"\W\d", string3))

# Find whitespace
print(re.findall(r"on\ssale", string3))

# Find non-whitespace
print(re.findall(r"robot\Sconstumes", string3))

['$5']
['on sale', 'on sale']
['robot-constumes']


In [3]:
# Replace
my_string = "Hello, World!"
new_string = re.sub(r"Hello", "Hi", my_string)
print(new_string)  # Output: Hi, World!

Hi, World!


### 6. Lambda Functions and Error-Handling

In [7]:
raise_to_power = lambda x, y: x**y
raise_to_power(2,3)

8

In [13]:
nums = [48, 6, 9, 21, 1]

# map(): returns an iterator object which avoids unnecessary memory usage
# simple functionalities to be anonyumously embedded within larger expressions

square_all = map(lambda num: num**2, nums)  
print(square_all)
print(list(square_all))

[2304, 36, 81, 441, 1]


In [14]:
add_bangs = lambda str: str + '!!!'
add_bangs('hello')

'hello!!!'

In [15]:
echo_word = lambda word1, echo: word1*echo
result = echo_word('hey', 5)
print(result)

heyheyheyheyhey
