# DataCamp Data Engineer Associate Certificate Prep
- https://app.datacamp.com/learn/fast-tracks/data-engineer-associate/plan?competency=2
- Focus on Competency 2, 3, and 5 (Python programming)

### Competency 2: Data Management in Python

1. Logic, Control Flow and Filtering
- Comparison Operators
- Boolean Operators

In [2]:
import numpy as np

# array(), a function part of the Numpy Library
# (): function call. []: a Python list. The function call array() convert the Pytyon list into a Numpy array.

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight/np_height**2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [29]:
# apply a Boolean indexing or boolean masking to the `bmi` array.

print(bmi[bmi>23])


# concise and comonly accepted
# `&` is a bitwise operator used for element-wise logical AND operations on arrays. 

print(bmi[(bmi > 21) & (bmi < 24)])

# for explicitness or complex conditions. Masked array:
print(bmi[np.logical_and(bmi > 21, bmi < 24)])
print(bmi[np.logical_not(bmi <= 21, bmi >= 24)])

# boolean array
print(np.logical_and(bmi > 21, bmi < 24))
print(np.logical_not(bmi <= 21, bmi >= 24))

[24.7473475]
[21.85171573 21.75028214 21.44127836]
[21.85171573 21.75028214 21.44127836]
[21.85171573 21.75028214 24.7473475  21.44127836]
[ True False  True False  True]
[ True False  True  True  True]


In [5]:
bmi>23

array([False, False, False,  True, False])

In [14]:
print(True == 1)
print(True > False)

True
True


In [27]:
my_kitchen = 18.0
your_kitchen = 14.0

print(my_kitchen > 10 and my_kitchen < 18)
print(my_kitchen < 14 and my_kitchen > 17)
print(my_kitchen*2 < your_kitchen*3)



False
False
True


2. Transforming DataFrames
- Sorting and subsetting
- Introducing DataFrames

True